BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: miles_input
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: "Up"
            Button:
                text: "Down"
    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: 'convert m to km'
    BoxLayout:
        orientation: 'horizontal'
        Label:
            text: 'henlo'
